name: Deploy Web App (Azure SWA)

on:
  push:
    branches: [dev]
    paths:
      - "apps/web/**"
      - ".github/workflows/swa-app-deploy.yml"

  workflow_dispatch:
    inputs:
      target:
        description: "Deploy target environment"
        required: true
        default: dev
        type: choice
        options: [dev, prod]

permissions:
  contents: read

concurrency:
  group: swa-web-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    # dev for dev-branch pushes; for manual runs choose dev/prod
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'dev' }}

    defaults:
      run:
        working-directory: apps/web

    env:
      # Build-time env vars for Vite (from the GitHub Environment secrets)
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: apps/web/package-lock.json

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "apps/web/dist"
          output_location: ""
          skip_app_build: true
